### ISSUE TITLE
Capture song metadata for use in beat saber level data

### ISSUE THREAD

**Issue by ryanwersal** [beatsabertools/sabergen#10]
Consider using [mutagen](https://github.com/quodlibet/mutagen). Maybe there are other possibilities? The goal is to be rather format agnostic though we could just support ogg assuming ffmpeg (or other process we use) carries over the necessary metadata.

**Comment by zvekovius** [comment]
Since we are using it for only metadata, seems fine to leave it in whatever format it is in to scrape that data before forcing things to ogg.

Trying to use anything past metadata seems bad though if we are converting to anything other than the original format.

**Comment by ryanwersal** [comment]
Agreed. I was thinking of using it explicitly for the incoming file. I liked the notion of using the original file since it should be most "pure" in terms of any loss of metadata (I'm not sure what all format support what all metadata etc).

**Comment by zvekovius** [comment]
Looks good to me. 
I like the separation of BeatSaberSong to output, core, and conversion.

I think our pyplot stuff should be moved to output. It is a user output.

Per our human conversation, load should probably also just do the heavy lift and return one nice canonical version of the song with all of the attributes.. Just do one slow expensive call, then have it for everything else we do in a fast format.
We also talked about limiting this. Whatever makes sense to store all the time vs. generate on call.

**Comment by zvekovius** [comment]
Uh ^ that goes to the PR. But w/e
