### ISSUE TITLE
add python3-tk to pipenv

### ISSUE THREAD

**Issue by zvekovius** [beatsabertools/sabergen#9]
matplotlib requires some sort of gui drawing lib. 
python3-tk seems to be the cool thing. 
probably add that to the pipenv since it isn't a hard depends of current packages, but needed to run the CLI otherwise.

**Comment by ryanwersal** [comment]
I wasn't able to find a way to get this into the `Pipfile` - it seems Tkinter is just assumed to be implicitly available with any given Python install (including virtualenvs). Thoughts?

**Comment by zvekovius** [comment]
Turns out python ships with it standard like, but requires some C++ code to be installed via apt on Linux. They must leverage other stuff on MacOSX & windows since ya'll report not having issues. 
I'll update the readme with linux specific instructions for that part and make sure we include it with our packaging process eventually.

**Comment by ryanwersal** [comment]
I ended up just swapping to the `WebAgg` backend that requires Tornado due to issues with GH Actions. This should resolve this for now (though still need to figure out the sndfile business on macOS and Windows).
